# Generated by Django 4.2 on 2023-04-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_id', models.IntegerField()),
                ('corpus_name', models.CharField(max_length=20)),
                ('corpus_type', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('source_type', models.CharField(max_length=20)),
                ('vendor', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=20)),
            ],
        ),
    ]
