From python:3.7
WORKDIR /package
MAINTAINER Siddhant
RUN pip3 install dvc
RUN pip3 install psycopg2-binary
RUN pip3 install numpy
RUN pip3 install datasets
RUN pip3 install typer
RUN pip3 install django
RUN pip3 install django-cors-headers
RUN pip3 install djangorestframework
RUN pip3 install djangorestframework-simplejwt
RUN python3 -m pip install -e .

CMD ["echo", "Udops installed"]

